<template id="template-menu-new-question">
    <div class="dropdown-content">
        <button type="button" data-type="singleChoice" class="btn">
            <?=LANG["singleChoice"]?></button>
        <button type="button" data-type="multiChoice" class="btn">
            <?=LANG["multiChoice"]?></button>
        <button type="button" data-type="shortAnswer" class="btn">
            <?=LANG["shortAnswer"]?></button>
        <button type="button" data-type="fillIn" class="btn">
            <?=LANG["fillIn"]?></button>
    </div>
</template>
