<?php
    $formType ??= "create";
    if ($formType === "update") {
        $formTitle = LANG["editDocument"];
        $formAction = "/app/forms/create_document.php?updateID={$_GET["documentID"]}";
    }
    else {
        $formTitle = LANG["createNewDocument"];
        $formAction = "/app/forms/create_document.php";
    }
?>
<form action="<?=$formAction?>" method="post"
    class="form form-validate">
    <button type="button" data-overlay="create-document" class="btn btn-close-overlay">
        <i class="bi bi-x-lg"></i></button>

    <h1><?=$formTitle?></h1>

    <label for="name"><?=LANG["name"]?>*</label>
    <input autofocus required type="text" name="name" id="name"
        pattern="<?=trim(DocumentModel::REGEX_VALID_NAME, "/")?>"
        title="<?=LANG["invalidDocumentName"]?>" class="input"
        value="<?=LANG["defaultDocumentName"]?>">

    <label for="type"><?=LANG["type"]?>*</label>
    <select name="type" id="type" class="input input-novalidate">
        <option value="exam"><?=LANG["exam"]?></option>
        <option value="form"><?=LANG["form"]?></option>
    </select>

    <label for="visibility"><?=LANG["visibility"]?>*</label>
    <select name="visibility" id="visibility" class="input input-novalidate">
        <option value="public"><?=LANG["public"]?></option>
        <option value="private"><?=LANG["private"]?></option>
        <option value="unlisted"><?=LANG["unlisted"]?></option>
    </select>

    <label for="num-max-submissions"><?=LANG["numMaxSubmissions"]?></label>
    <input type="number" name="numMaxSubmissions"
        id="num-max-submissions" min="1" max="100"
        title="<?=LANG["invalidNumMaxSubmissions"]?>" class="input">

    <label for="deadline-datetime"><?=LANG["deadlineDatetime"]?></label>
    <input type="datetime-local" name="deadlineDatetime"
        id="deadline-datetime" class="input input-novalidate">

    <?php readfile("local_timezone.html", use_include_path:true); ?>

    <button class="btn"><?=$formTitle?></button>

    <div class="form-error-msg"></div>
</form>
<script>
<?php
    if ($formType === "update") {
        foreach (DocumentModel::UPDATE_VARS as $inputName) {
            $var = $document->$inputName;
            echo "document.forms[0].elements['$inputName'].defaultValue = '$var';\n";
        }
    }
?>
</script>
