<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
<link rel="stylesheet" href="/static/master.css">

<script>
    window.addEventListener("load", () => {
        // Set theme:
        const themeClassName = "<?=$preferences["theme"]?>-theme";
        document.documentElement.classList.add(themeClassName);

        // Set root element lang attribute:
        const lang = "<?=$preferences["lang"]?>";
        document.documentElement.lang = lang;

        // Localize & timezone-adjust all timestamps:
        const dateFormatOptions = {
            year: "numeric",
            month: "long",
            day: "numeric",
        };
        const timeFormatOptions = {
            hour: "numeric",
            minute: "numeric",
        };
        const dateTimeFormatOptions
            = {...dateFormatOptions, ...timeFormatOptions};

        for (const timestampEl of document.getElementsByClassName("timestamp")) {
            // When passing an UTC timestamp to the Date ctor, it adjusts it to
            // the local timezone.
            const adjustedTimestamp = new Date(timestampEl.innerText + " UTC");
            let timestampFormatOptions;
            switch(timestampEl.dataset.format) {
                case "date": timestampFormatOptions = dateFormatOptions; break;
                case "time": timestampFormatOptions = timeFormatOptions; break;
                case "datetime":
                default: timestampFormatOptions = dateTimeFormatOptions;
            }
            timestampEl.innerText
                = adjustedTimestamp.toLocaleString(lang, timestampFormatOptions);
        }
    });
</script>
