<a id="title-wrapper" href="/views/index.phtml">
    <img src="/static/favicons/favicon.ico" alt="Exam Engine favicon" style="display: inline-block;">
    <h1 id="title">Exam Engine</h1>
</a>

<nav>
    <a class="btn nav-item" href="/views/index.phtml">
        <i class="bi bi-house"></i> <?=LANG["homePage"]?></a>
    <?php if (! isset($_SESSION["userID"])): ?>
        <a class="btn nav-item" href="/views/sign_up.phtml">
            <i class="bi bi-person-add"></i> <?=LANG["signUp"]?></a>
        <a class="btn nav-item" href="/views/log_in.phtml">
            <i class="bi bi-box-arrow-right"></i> <?=LANG["logIn"]?></a>
    <?php endif; ?>
    <a class="btn nav-item" href="/views/profile.phtml">
        <i class="bi bi-person-circle"></i> <?=LANG["profile"]?></a>
</nav>
