<?php
require_once "config.php";
session_start();

$documentID = $_GET["documentID"];
$genMode = $_GET["genmode"] ?? "view";
?>
<!DOCTYPE html>
<html>
<head>
    <?php include "head.phtml"; ?>
    <title><?=LANG["document"]?> &bull; Exam Engine</title>

    <link rel="stylesheet" href="/static/document.css">
    <script type="module" src="/static/document_app/generator.js"></script>
</head>
<body>
<?php readfile("question_element.html", use_include_path:true); ?>
<?php include "document_menus.phtml"; ?>
<header>
    <?php include "header.phtml"; ?>
</header>
<main>
<section>
    <h1 id="document-name"></h1>

    <form id="document-area"></form>

    <div class="input-group">
        <button id="btn-document-submit" class="btn">
            <i class="bi bi-pencil"></i>
            <?php
                echo match ($genMode) {
                    "view" => LANG["submitDocument"],
                    "edit" => LANG["editDocument"],
                };
            ?>
        </button>

        <?php if ($genMode === "edit"): ?>
            <a class="btn warning" href="/views/document_details.phtml?documentID=<?=$documentID?>">
                <i class="bi bi-trash"></i> <?=LANG["discardChanges"]?></button>
            </a>
        <?php endif; ?>
        </div>
</section>
</main>
<footer>
    <?php include "footer.phtml"; ?>
</footer>
</body>
</html>
