<?php
require_once "config.php";
session_start();

$documentID = $_GET["documentID"];
?>
<!DOCTYPE html>
<html>
<head>
    <?php include "head.phtml"; ?>
    <title><?=LANG["document"]?> &bull; Exam Engine</title>

    <link rel="stylesheet" href="/static/document.css">
    <script type="module" src="/static/document_app/generator.js"></script>
</head>
<body>
<?php readfile("question_element.html", use_include_path:true); ?>
<header>
    <?php include "header.phtml"; ?>
</header>
<main>
<section>
    <h1 id="document-name"></h1>

    <div id="document-area">
        <button id="btn-document-submit" class="btn">
            <?=LANG["submitDocument"]?>
        </button>
    </div>
</section>
</main>
<footer>
    <?php include "footer.phtml"; ?>
</footer>
</body>
</html>
