<?php
require_once "config.php";
session_start();

$documentID = $_GET["documentID"];
$document = DocumentModel::ctorLoad($documentID);

if (! $document)
    die("document not found!");
?>
<!DOCTYPE html>
<html>
<head>
    <?php include "head.phtml"; ?>
    <title><?=LANG["documentDetails"]?>
        &bull; <?=$document->name?> &bull; Exam Engine</title>

    <script defer src="/static/js/datetime_formatter.js"></script>

    <script>
        function datetimeLocalISOString(datetimeUTC)
        {
            if (! datetimeUTC)
                return;
            const date = new Date(datetimeUTC + " UTC");
            const timezoneOffsetMS = new Date().getTimezoneOffset() * 60 * 1000;
            const localDate = new Date(date.getTime() - timezoneOffsetMS);
            return localDate.toISOString().split('.')[0];
        }
    </script>
</head>
<body>
<header>
    <?php include "header.phtml"; ?>
</header>
<main>
<section>
    <h1><?=LANG["documentDetails"]?>: <em><?=$document->name?></em></h1>

    <!-- Document details  -->
    <ul>
        <li><?=LANG["type"], ": ",
            LANG[$document->type]?></li>
        <li><?=LANG["visibility"], ": ",
            LANG[$document->visibility]?></li>
        <li><?=LANG["numMaxSubmissions"], ": ",
            $document->numMaxSubmissions ?? "N/A"?></li>
        <li><?=LANG["deadlineDatetime"]?>:
            <span class="timestamp"><?=$document->deadlineDatetime?></span></li>
        <li><?=LANG["creationDate"]?>:
            <span class="timestamp" data-format="date">
            <?=$document->creationDate?></span></li>
    </ul>

    <div class="form-error-msg"><?=Util::getFormError();?></div>

    <div class="input-group">
        <a class="btn" href="/views/document.phtml?documentID=<?=$documentID?>">
            <i class="bi bi-file-earmark"></i> <?=LANG["openDocument"]?></a>
<?php if ($document->isAuthorized()): ?>
        <button class="btn btn-open-overlay" data-overlay="create-document">
            <i class="bi bi-pencil"></i> <?=LANG["editDetails"]?></button>
        <a class="btn" href="/views/document.phtml?genmode=edit&documentID=<?=$documentID?>">
            <i class="bi bi-pencil"></i> <?=LANG["editQuestions"]?></a>
        <button class="btn warning btn-open-overlay"
            data-overlay="confirm-delete-document">
            <i class="bi bi-trash"></i> <?=LANG["deleteDocument"]?></button>
    </div>
<?php endif; ?>
</section>
<section>
    <h1><?=LANG["documentSubmissions"]?></h1>

    <table>
    <?php
        $filter = "`documentID` = $documentID ORDER BY `submissionDate` DESC";

        $submissions = SubmissionModel::listSubmissions($filter);

        if (count($submissions)) {
            $headers = ["author", "submissionDate", "viewSubmission"];
            echo "<tr><th>", implode(
                "</th><th>", array_map(fn($x) => LANG[$x], $headers)), "</th></tr>";
        }
        else {
            echo "<p>", LANG["noSubmissions"], "</p>";
        }

        foreach ($submissions as $submission) {
            foreach ($submission as $key => &$val)
                $$key = $val;

            $username = "$firstName $lastName
                (<a href='/views/profile.phtml?userID=$userID'>@$username</a>)";

            $submissionLink = "<a href='/views/document.phtml?documentID=$documentID&submissionID=$submissionID?genmode=review'>view</a>";

            echo "\n<tr><td>", implode(
                "</td><td>", [$username, "<span class='timestamp'>$submissionDate</span>",
            $submissionLink]), "</td></tr>";
        }
    ?>
    </table>

</section>
</main>
<?php if ($document->isAuthorized()): ?>

<script defer src="/static/js/overlay.js"></script>

<!-- Start overlay -->
<div id="overlay-confirm-delete-document" class="overlay">
    <div>
        <button data-overlay="confirm-delete-document" class="btn btn-close-overlay">
            <i class="bi bi-x-lg"></i></button>

        <h1><?=LANG["deleteDocument"]?></h1>
        <p><?=LANG["deleteDocumentConfirmation"]?></p>
        <div class="input-group flex-center">
            <a href="/app/api/deleting.php?documentID=<?=$_GET["documentID"]?>"
                class="btn warning">
               <?=LANG["yes"]?>
            </a>
            <button data-overlay="confirm-delete-document"
                class="btn btn-close-overlay">
                <?=LANG["no"]?></button>
        </div>
    </div>
</div>
<!-- End overlay -->

<script defer src="/static/js/form_validation.js"></script>

<div id="overlay-create-document" class="overlay">
    <?php $formType = "update"; include "form_create_document.phtml"; ?>
</div>
<?php endif; ?>
<footer>
    <?php include "footer.phtml"; ?>
</footer>
</body>
</html>
