<?php
require_once "config.php";
session_start();
?>
<!DOCTYPE html>
<html>
<head>
    <?php include "head.phtml"; ?>
    <title><?=LANG["homePage"]?> &bull; Exam Engine</title>
</head>
<body>
<header>
    <?php include "header.phtml"; ?>
</header>
<main>
<section>
    <h1><?=LANG["homePage"]?></h1>

    <p><?=LANG["welcome"]?></p>
</section>
</main>
<footer>
    <?php include "footer.phtml"; ?>
</footer>
</body>
</html>
