<?php
require_once "config.php";
session_start();

if (! isset($_SESSION["userID"])) {
    Util::redirect("/views/log_in.phtml");
}
?>
<!DOCTYPE html>
<html>
<head>
    <?php include "head.phtml"; ?>
    <title><?=LANG["homePage"]?> &bull; Exam Engine</title>

    <script defer src="/static/js/form_validation.js"></script>
    <script defer src="/static/js/overlay.js"></script>
    <script defer src="/static/js/datetime_formatter.js"></script>
</head>
<body>
<header>
    <?php include "header.phtml"; ?>
</header>
<main>
<section>
    <h1><?=LANG["homePage"]?></h1>

    <p><?=LANG["welcome"]?></p>

    <div class="form-error-msg"><?=Util::getFormError();?></div>
</section>
<section>
    <h1><?=LANG["documents"]?></h1>

    <table id="documents-listing">
    <?php

        $filter = "`authorID` = {$_SESSION["userID"]} ORDER BY `creationDate`";

        $documents = DocumentModel::listDocuments($filter);

        if (count($documents)) {
            $headers = ["name", "type", "visibility", "deadlineDatetime", ];
            echo "<tr><th>", implode(
                "</th><th>", array_map(fn($x) => LANG[$x], $headers)), "</th></tr>";
        }
        else {
            echo "<p>", LANG["youHaveNoDocuments"], "</p>";
        }

        foreach ($documents as $document) {
            foreach ($document as $key => &$val)
                $$key = $val;

            $name = "<a href='/views/document_details.phtml?documentID=$ID'>$name</a>";
            $type = LANG[$type];
            $visibility = LANG[$visibility];
            $deadlineDatetime = "<span class='timestamp'>$deadlineDatetime</span>";
            # $username = "<a href='/views/user_details.phtml?userID=$authorID'>@$username</a>";
            # $author = "$firstName $lastName ($username)";

            echo "\n<tr><td>", implode(
                "</td><td>", [$name, $type, $visibility, $deadlineDatetime]), "</td></tr>";
        }
    ?>
    </table>

    <button class="btn btn-open-overlay" data-overlay="create-document">
        <i class="bi bi-plus-circle"></i> <?=LANG["createNewDocument"]?></button>
</section>
</main>
<footer>
    <?php include "footer.phtml"; ?>
</footer>
<div id="overlay-create-document" class="overlay">
    <?php include "form_create_document.phtml"; ?>
</div>
</body>
</html>
