<?php
require_once "config.php";
session_start();
?>
<!DOCTYPE html>
<html>
<head>
    <?php include "head.phtml"; ?>
    <title><?=LANG["logIn"]?> &bull; Exam Engine</title>
</head>
<body>
<header>
    <?php include "header.phtml"; ?>
</header>
<main class="form-focus-wrapper">
    <form class="form" action="/app/forms/log_in.php" method="post">
        <h1><?=LANG["logIn"]?></h1>

        <label for="username"><?=LANG["usernameOrEmail"]?></label>
        <input autofocus required class="input"
            type="text" name="usernameOrEmail" id="username-or-email">

        <label for="password"><?=LANG["password"]?></label>
        <input required class="input" type="password" name="password" id="password">

        <button class="btn"><?=LANG["logIn"]?></button>

        <?=Util::getFormError();?>
    </form>
</main>
<footer>
    <?php include "footer.phtml"; ?>
</footer>
</body>
</html>
