<?php
require_once "config.php";
session_start();
?>
<!DOCTYPE html>
<html>
<head>
    <?php include "head.phtml"; ?>
    <title><?=LANG["profile"]?> &bull; Exam Engine</title>

    <script defer src="/static/js/update_preferences.js"></script>
    <script defer src="/static/js/overlay.js"></script>
</head>
<body>
<header>
    <?php include "header.phtml"; ?>
</header>
<main>
<section>
    <h1><?=LANG["profile"]?></h1>

<?php if (isset($_SESSION["userID"])): ?>
    <?php
        // Load current user if logged in
        $user = UserModel::ctorLoad($_SESSION["userID"]);
        $fullName = $user->firstName . " " . $user->lastName;
    ?>

    <!-- User profile details  -->
    <h3><?=$user->firstName?> <?=$user->lastName?> (@<?=$user->username?>)</h3>
    <ul>
        <li><?=LANG["lastLogin"]?> <span class="timestamp" data-format="datetime">
            <?=$user->lastLoginTime?></span></li>
        <li><?=LANG["joined"]?> <span class="timestamp" data-format="date">
            <?=$user->creationDate?></span></li>
    </ul>

    <div class="input-group">
        <button class="btn btn-open-overlay" data-overlay="edit-profile">
            <i class="bi bi-pencil"></i> <?=LANG["editProfile"]?></button>
        <a class="btn" href="/app/forms/log_out.php">
            <i class="bi bi-escape"></i> <?=LANG["logOut"]?></a>
        <button class="btn warning btn-open-overlay"
            data-overlay="confirm-delete-profile">
            <i class="bi bi-trash"></i> <?=LANG["deleteAccount"]?></button>
    </div>
<?php else: ?>
    <p>
        <a href="http://localhost/views/log_in.phtml"><?=LANG["logInCTA1"]?></a>
        <?=LANG["logInCTA2"]?>
    </p>
<?php endif; ?>
</section>
<section>
    <h1><?=LANG["preferences"]?></h1>
    <ul>
        <li>
            <?=LANG["theme"]?>:
            <select id="theme" class="input config-dropdown">
                <option value="dark"><?=LANG["dark"]?></option>
                <option value="light"><?=LANG["light"]?></option>
            </select>
        </li>
        <li>
            <?=LANG["lang"]?>:
            <select id="lang" class="input config-dropdown">
                <option value="hr"><?=LANG["hr"]?></option>
                <option value="en"><?=LANG["en"]?></option>
            </select>
        </li>
        <li>
            <?=LANG["accentColor"]?>:
            <input type="color" id="accentColor" class="input config-dropdown" value="#FF0000">
        </li>
    </ul>

    <a class="btn" href="/app/api/update_preferences.php?name=reset">
        <i class="bi bi-x-circle"></i> <?=LANG["resetPreferences"]?></a>
</section>
<?=Util::getFormError();?>
</main>

<?php if (isset($_SESSION["userID"])): ?>

<div id="overlay-confirm-delete-profile" class="overlay">
    <div>
        <button data-overlay="confirm-delete-profile" class="btn btn-close-overlay">
            <i class="bi bi-x-lg"></i></button>

        <h1><?=LANG["deleteAccount"]?></h1>
        <p><?=LANG["deleteAccountConfirmation"]?></p>
        <div class="input-group flex-center">
            <a href="/app/forms/delete_user.php" class="btn warning">Yes</a>
            <button data-overlay="confirm-delete-profile"
                class="btn btn-close-overlay">
                No</button>
        </div>
    </div>
</div>

<script defer src="/static/js/form_validation.js"></script>

<div id="overlay-edit-profile" class="overlay">
    <form action="/app/forms/sign_up.php?update" method="post" class="form form-validate">
        <button type="button" data-overlay="edit-profile" class="btn btn-close-overlay"
            onclick="this.parentElement.reset();">
            <i class="bi bi-x-lg"></i></button>

        <h1><?=LANG["editProfile"]?></h1>

        <label for="username"><?=LANG["username"]?></label>
        <input autofocus required type="text" name="username" id="username"
            pattern="<?=trim(UserModel::REGEX_VALID_USERNAME, "/")?>"
            title="<?=LANG["invalidUsername"]?>" class="input"
            value="<?=$user->username?>">

        <label for="email"><?=LANG["email"]?></label>
        <input required type="email" name="email" id="email" class="input"
            title="<?=LANG["invalidEmail"]?>"
            value="<?=$user->email?>">

        <label for="first-name"><?=LANG["firstName"]?></label>
        <input required type="text" name="firstName" id="first-name"
            pattern="<?=trim(UserModel::REGEX_VALID_NAME, "/")?>"
            title="<?=LANG["invalidName"]?>" class="input"
            value="<?=$user->firstName?>">

        <label for="last-name"><?=LANG["lastName"]?></label>
        <input required type="text" name="lastName" id="last-name"
            pattern="<?=trim(UserModel::REGEX_VALID_NAME, "/")?>"
            title="<?=LANG["invalidName"]?>" class="input"
            value="<?=$user->lastName?>">

        <button class="btn"><?=LANG["save"]?></button>

        <div class="form-error-msg"></div>
    </form>
</div>
<?php endif; ?>
<footer>
    <?php include "footer.phtml"; ?>
</footer>
</body>
</html>
