<?php
require_once "config.php";
session_start();
?>
<!DOCTYPE html>
<html>
<head>
    <?php include "head.phtml"; ?>
    <title><?=LANG["profile"]?> &bull; Exam Engine</title>

    <script defer src="/static/js/update_preferences.js"></script>
    <script defer src="/static/js/datetime_formatter.js"></script>
</head>
<body>
<header>
    <?php include "header.phtml"; ?>
</header>
<main>
<section>
    <h1><?=LANG["profile"]?></h1>

<?php if (isset($_SESSION["userID"])): ?>
    <?php
        # Load current user if logged in
        $user = UserModel::ctorLoad($_SESSION["userID"]);
        $fullName = $user->firstName . " " . $user->lastName;
    ?>

    <!-- User profile details  -->
    <h3><?=$user->firstName?> <?=$user->lastName?> (@<?=$user->username?>)</h3>
    <ul>
        <li><?=LANG["lastLogin"]?> <span class="timestamp" data-format="datetime">
            <?=$user->lastLoginTime?></span></li>
        <li><?=LANG["joined"]?> <span class="timestamp" data-format="date">
            <?=$user->creationDate?></span></li>
    </ul>

    <div class="input-group">
        <button class="btn btn-open-overlay" data-overlay="edit-profile">
            <i class="bi bi-pencil"></i> <?=LANG["editProfile"]?></button>
        <a class="btn" href="/app/forms/log_out.php">
            <i class="bi bi-escape"></i> <?=LANG["logOut"]?></a>
        <button class="btn warning btn-open-overlay"
            data-overlay="confirm-delete-profile">
            <i class="bi bi-trash"></i> <?=LANG["deleteAccount"]?></button>
    </div>
<?php else: ?>
    <p>
        <a href="http://localhost/views/log_in.phtml"><?=LANG["logInCTA1"]?></a>
        <?=LANG["logInCTA2"]?>
    </p>
<?php endif; ?>

<div class="form-error-msg"><?=Util::getFormError();?></div>

</section>
<section>
    <h1><?=LANG["preferences"]?></h1>
    <ul>
        <li>
            <?=LANG["theme"]?>:
            <select id="theme" class="input config-dropdown">
                <option value="dark"><?=LANG["dark"]?></option>
                <option value="light"><?=LANG["light"]?></option>
            </select>
        </li>
        <li>
            <?=LANG["lang"]?>:
            <select id="lang" class="input config-dropdown">
                <option value="hr"><?=LANG["hr"]?></option>
                <option value="en"><?=LANG["en"]?></option>
            </select>
        </li>
        <li>
            <?=LANG["accentColor"]?>:
            <input type="color" id="accentColor" class="input config-dropdown" value="#FF0000">
        </li>
    </ul>

    <a class="btn" href="/app/api/update_preferences.php?name=reset">
        <i class="bi bi-x-circle"></i> <?=LANG["resetPreferences"]?></a>
</section>
</main>

<?php if (isset($_SESSION["userID"])): ?>

<script defer src="/static/js/overlay.js"></script>

<div id="overlay-confirm-delete-profile" class="overlay">
    <div>
        <button data-overlay="confirm-delete-profile" class="btn btn-close-overlay">
            <i class="bi bi-x-lg"></i></button>

        <h1><?=LANG["deleteAccount"]?></h1>
        <p><?=LANG["deleteAccountConfirmation"]?></p>
        <div class="input-group flex-center">
            <a href="/app/api/deleting.php?user" class="btn warning">
                <?=LANG["yes"]?></a>
            <button data-overlay="confirm-delete-profile"
                class="btn btn-close-overlay">
                <?=LANG["no"]?></button>
        </div>
    </div>
</div>

<script defer src="/static/js/form_validation.js"></script>

<div id="overlay-edit-profile" class="overlay">
    <?php $formType = "update"; include "form_sign_up.phtml"; ?>
</div>
<?php endif; ?>
<footer>
    <?php include "footer.phtml"; ?>
</footer>
</body>
</html>
