<?php
require_once "config.php";
session_start();
?>
<!DOCTYPE html>
<html>
<head>
    <?php include "head.phtml"; ?>
    <title><?=LANG["homePage"]?> &bull; Exam Engine</title>
</head>
<body>
<header>
    <?php include "header.phtml"; ?>
</header>
<main>
    <?php
        $user = UserModel::ctorLoad($_SESSION["userID"]);
        $fullName = $user->firstName . " " . $user->lastName;
    ?>

    <h2><?=$fullName?> (@<?=$user->username?>)</h2>
    <h4><?=LANG["lastLogin"]?> <?=$user->lastLoginTime?>.</h4>
    <h4><?=LANG["joined"]?> <?=$user->creationDate?>.</h4>

    <a href="/app/forms/log_out.php"><?=LANG["logOut"]?></a>
</main>
<footer>
    <?php include "footer.phtml"; ?>
</footer>
</body>
</html>
