<?php
require_once "config.php";
session_start();
?>
<!DOCTYPE html>
<html>
<head>
    <?php include "head.phtml"; ?>
    <title><?=LANG["signUp"]?> &bull; Exam Engine</title>
</head>
<body>
<header>
    <?php include "header.phtml"; ?>
</header>
<main class="form-focus-wrapper">
    <form action="/app/forms/sign_up.php" method="post" class="form">
        <h1><?=LANG["signUp"]?></h1>

        <label for="username"><?=LANG["username"]?></label>
        <input autofocus required type="text" name="username" id="username"
            pattern="<?=trim(UserModel::REGEX_VALID_USERNAME, "/")?>"
            title="<?=LANG["invalidUsername"]?>" class="input">

        <label for="email"><?=LANG["email"]?></label>
        <input required type="email" name="email" id="email" class="input">

        <label for="password"><?=LANG["password"]?></label>
        <input required type="password" name="password" id="password"
            pattern="<?=trim(UserModel::REGEX_VALID_PASSWORD, "/")?>"
            title="<?=LANG["invalidPassword"]?>" class="input">

        <label for="first-name"><?=LANG["firstName"]?></label>
        <input required type="text" name="firstName" id="first-name"
            pattern="<?=trim(UserModel::REGEX_VALID_NAME, "/")?>"
            title="<?=LANG["invalidName"]?>" class="input">

        <label for="last-name"><?=LANG["lastName"]?></label>
        <input required type="text" name="lastName" id="last-name"
            pattern="<?=trim(UserModel::REGEX_VALID_NAME, "/")?>"
            title="<?=LANG["invalidName"]?>" class="input">

        <button class="btn"><?=LANG["signUp"]?></button>

        <?=Util::getFormError();?>
    </form>
</main>
<footer>
    <?php include "footer.phtml"; ?>
</footer>
</body>
</html>
