<?php
require_once "config.php";
session_start();
?>
<!DOCTYPE html>
<html>
<head>
    <?php include "head.phtml"; ?>
    <title><?=LANG["signUp"]?> &bull; Exam Engine</title>

    <script defer src="/static/js/password_peak_btn.js"></script>
    <script defer src="/static/js/form_validation.js"></script>
</head>
<body>
<header>
    <?php include "header.phtml"; ?>
</header>
<main>
<!-- Start form_sign_up.phtml -->
    <?php include "form_sign_up.phtml"; ?>
<!-- End form_sign_up.phtml -->
</main>
<footer>
    <?php include "footer.phtml"; ?>
</footer>
</body>
</html>
